name: Release to NPM

on:
  release:
    types: [released]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Activate corepack
        run: corepack enable

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - uses: simenandre/publish-with-yarn@v1
        with:
          npm-auth-token: ${{ secrets.npm_token }}
